import{S as P,a as u,i as c}from"./assets/vendor-DTWVMNYS.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const f=document.querySelector(".gallery");let x=new P(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const t=o.map(n=>{const{webformatURL:s,largeImageURL:e,tags:r,likes:i,views:b,comments:v,downloads:S}=n,q=r.split(", ").join(", ");return`<li class="photo-card">
    <a href="${e}">
    <img src="${s}" alt="${r}" />
    </a>
    <div class="photo-info">
        <p>Tags: ${q}</p>
        <p>Likes: ${i}</p>
        <p>Views: ${b}</p>
        <p>Comments: ${v}</p>
        <p>Downloads: ${S}</p>
    </div>
</li>
`}).join("");f.insertAdjacentHTML("beforeend",t),x.refresh()}function E(){f.innerHTML=""}function m(){document.querySelector(".loader").classList.remove("hidden")}function h(){document.querySelector(".loader").classList.add("hidden")}function g(){document.querySelector(".btn").classList.remove("hidden")}function y(){document.querySelector(".btn").classList.add("hidden")}const T="51798478-5201f32441bd2af0c91072e2d";u.defaults.baseURL="https://pixabay.com/api/";const d=15;async function L(o,t){const n={key:T,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await u.get("",{params:n})).data}const w=document.querySelector(".form"),$=w.elements["search-text"],I=document.querySelector(".btn");let l="",a=1;w.addEventListener("submit",async o=>{if(o.preventDefault(),y(),E(),l=$.value.trim(),a=1,!l){c.error({title:"Error",message:"The search box is empty. Try again!"});return}try{m();const t=await L(l,a);if(t.hits.length===0){c.warning({title:"Oops",message:"No images found. Try another query!"});return}p(t.hits),t.totalHits>d&&g()}catch{c.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{h()}});I.addEventListener("click",async()=>{a++,m();try{const o=await L(l,a);if(o.hits.length>0){const t=(a-1)*d;p(o.hits);const s=document.querySelectorAll(".gallery li")[t];if(s){const e=s.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}a*d>=o.totalHits?(y(),c.info({title:"End",message:"We're sorry, but you've reached the end of search results."})):g()}catch{c.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{h()}});
//# sourceMappingURL=index.js.map
